name: deploy to github

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
    branches: [ "main", "Oct2024" ]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: github-pages

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Run
        env:
          TOKEN: ${{ secrets.TOKEN }}
          GUILDID: ${{ secrets.GUILDID }}
          CLIENTID: ${{ secrets.CLIENTID }}
        run: |
          touch .env
          echo TOKEN=${{ secrets.TOKEN }} >> .env
          echo GUILDID=${{ secrets.GUILDID }} >> .env
          echo CLIENTID=${{ secrets.CLIENTID }} >> .env
          npm install
          node .